development:	
     "Library of Congress Names" : '/authorities/search/loc/names'
     "FAST" : '/authorities/search/assign_fast/all'
production:	
     "Library of Congress Names" : '/authorities/search/loc/names'
     "FAST" : '/authorities/search/assign_fast/all'